### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-jax-rs-reactive-client#11]
- Elaborate on the rx() method, what it is, why it used etc.

- "If you want to learn more about MicroProfile Rest Client, you can read the Consuming RESTful services with template interfaces guide." -- This seems to be a copy and paste error or miss?

- Consider explaining (via a summary) the changes before asking users to replace the files.  This should help with understanding and comparing the before and after.

- The text mentioned an averageResult attribute but this is not shown in the sample output?

**Comment by jonathanxue** [comment]
- rx() is explained as well as alternative invokers
- copy error is fixed
- small explanation added before asking user to change files
- averageResult is mentioned to not appear in initial output, before jobs are created
