### ISSUE TITLE
Show working with a third-party library

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-jax-rs-reactive-client#12]
This is one of the main benefits of using reactive JAX-RS client.  We should cover this in the guide.

> Instead of using a CompletionStage return type, JAX-RS allows you to use a type from a third-party library such as RxJava. You can achieve this by passing the custom type into your call to rx().

**Comment by jonathanxue** [comment]
Addressed, guide includes usage of Jersey
