### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-jax-rs-reactive-client#34]
- [x] Rewrite the first paragraph of the "What you'll learn" section
    - too technical at the beginning
    - move the main content to the end of the section
- [x]  revisit the whole guide to add type for `AnyObject`, e,g, `AnyObject` interface, `AnyObject` class, etc...
- **Using the default reactive JAX-RS client**
  - [x] rewrite the first paragraph
    - The following statement is no need:
      - "The application functions similarly to the one created in our Consuming RESTful services asynchronously with template interfaces guide. "
- [x] "Updating the client to support third-party objects" -> "Updating the client to use third-party objects"

**Comment by jonathanxue** [comment]
feedback addressed
