### ISSUE TITLE
Misspelling in Java code

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/draft-guide-jax-rs-reactive-client#41]
https://github.com/OpenLiberty/draft-guide-jax-rs-reactive-client/blob/4006b90eb0ab030f7a32d2b78cc51fec4aeaeb6c/finish/job/src/main/java/io/openliberty/guides/job/JobResource.java#L91

Noticed it here, will probably exist in multiple references

**Comment by gkwan-ibm** [comment]
the app will be changed
