### ISSUE TITLE
Dev content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-jax-rs-reactive-client#43]
- **"What is reactive programming?"**
  - [x] rewrite
- **What you will learn**
  - [x] -> **What you'll learn**
  - [x] the diagram is a small, need to improve it
- **Additional Prerequisites**
  - [x] should be same as the async guide
- **Using the default reactive JAX-RS client**
  - Some content is not right, e.g. the last 2 paragraph; "The classes changed are..."
  - [x] Rewrite the whole section to explain InventoryClient and then QueryResource individually.
- **Updating the client to use third-party objects**
  - [x] Rewrite
- **Updating the JAX resources**
  - " The countdownLatch.await() will ensure that the function will only return a value once ..." is not right
  - [x] Rewrite
- **Building and running the application**
  - [x] the query command is wrong under "Run the following commands to containerize the microservices:"
  - [ ] add the instruction like the async guide to check the app ready
- [x] format the QueryServiceIT.java better so that no wrapped line
  
Note: I updated lgdev dev-ui.devmode to show `dev-tiago2`. The draft site is showing dev branch.

**Comment by TiagoF99** [comment]
> add the instruction like the async guide to check the app ready

I dont think this is a good way of checking that the application is ready. The output when the application is ready is as follows: 
<img width="1440" alt="Screen Shot 2020-06-24 at 10 23 05 AM" src="https://user-images.githubusercontent.com/45250015/85592266-048a6000-b614-11ea-92cc-f19bf521accf.png">
As you can see, users have to dig through many lines of log output to be able to locate ```Host d95127348814 was updated: CpuLoadAverage: {"hostname":"d95127348814","loadAverage":14.7}```. I was quite confused at first as well. I think it would be much easier and more efficient to just tell them to go to the endpoint and when it is ready, they will see a json output. This is like how I have outlined it in my guide. This also seems to be whats consistent with some of the other guides (E.g https://openliberty.io/guides/rest-client-java.html#running-the-application)

**Comment by TiagoF99** [comment]
- the rest of the feedback has been addressed and is pending review. Issues outlined in https://github.com/OpenLiberty/draft-guide-jax-rs-reactive-client/issues/38 were also taken into consideration.

**Comment by gkwan-ibm** [comment]
- **What is reactive programming?**
  - [ ] reword the first statement
    - sentence structure seems not right that there are 2 "and"
    - the words too close from other doc
- **What you’ll learn**
  - [ ] "Consuming RESTful services with template interfaces" and the link -> "Creating reactive Java microservices" guide
- **Using the default reactive JAX-RS client**
  - [ ] "The QueryResource class is use ..." -> "The QueryResource class is used..."
  - [ ] "hotspot file=0]InventoryClient" is shown
- **Building and running the application**
  - [ ] no need to have the curl instruction because the link `http://localhost:9080/query/systemLoad` can acheive
- at the top of the README.adoc 
  - [ ] `:page-related-guides:` should be `['microprofile-reactive-messaging', 'microprofile-rest-client-async']`
  - [ ] update `:page-seo-title:` as the async guide, at least the front part
  - [ ] update `:page-seo-description:` as the async guide, at least the front part

**Comment by TiagoF99** [comment]
- feedback has been addressed
