### ISSUE TITLE
The term is not fixed in the title and the description

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-jax-rs-reactive-client#6]
- [x] `JAX-RS reactive client` is not used in the following:
```
:page-description: Learn how to use JAX-RS reactive Rest client to invoke RESTful microservices over HTTP asynchronously.
:page-seo-description: A tutorial on how to consume Rest services asynchronously with the reactive JAX-RS client.
...
= Consuming RESTful services using the reactive JAX-RS client
```

- [x] seo title is not right
`:page-seo-title: Consuming Rest services asynchronously`

**Comment by yeekangc** [comment]
I find reactive JAX-RS client to be a better term.  Unless JAX-RS reactive client is used officially somewhere, I suggest considering reactive JAX-RS client.

**Comment by evelinec** [comment]
This had been reassigned to @jonathanxue.

**Comment by jonathanxue** [comment]
addressed
