### ISSUE TITLE
Guide inconsistency

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/draft-guide-jax-rs-reactive-client#7]
The guide states to replace a file:
![image](https://user-images.githubusercontent.com/26514093/64534918-5c094a80-d2e4-11e9-8c2c-193486ed1b80.png)
and afterwards explains that the replacement includes changing some methods.

However, when looking inside the `start/` directory, the file doesn't exist, see below:
![image](https://user-images.githubusercontent.com/26514093/64534987-7fcc9080-d2e4-11e9-9b1f-c79275acbd65.png)

So either reword to tell the user to create the file instead of replace, or put in an initial file to be replaced.

Same problem exists right after with the `gateway/src/main/java/io/openliberty/guides/gateway/JobGatewayResource.java` file

Additionally, throughout other guides, we have a separate section for 'Additional Prereqs' where we include Docker etc. but in this guide, it just tells the user to install Docker in the middle of the guide, see below: 
![image](https://user-images.githubusercontent.com/26514093/64535566-86a7d300-d2e5-11e9-8a63-8c90936d7347.png)

**Comment by jonathanxue** [comment]
issue addressed
