### ISSUE TITLE
Linux test fails

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/draft-guide-jax-rs-reactive-client#9]
OS: `Linux v4.18.0-15-generic, Ubuntu 18.04.2 LTS`
Maven: `Apache Maven 3.6.0`
Java: `OpenDJK 11.0.4`

Running the `mvn clean install` command in the `start/` directory results in the following error:
![image](https://user-images.githubusercontent.com/26514093/64538259-51ea4a80-d2ea-11e9-9f63-ceef2aad5863.png)

**Comment by jonathanxue** [comment]
addressed
